apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: catconsumer
  annotations:
    version: v0.0.1
    description: 'consumes a message and sends one to catcomponent'
spec:
  components:
    - name: catconsumer
      type: component
      properties:
        image: file://./build/cat_consumer_s.wasm
        id: catconsumer
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            instances: 1
        # Establish a unidirectional link to the messaging capability provider (powered by NATS),
        # so the `echo` component can make use of messaging interface functionality
        # (i.e. making interacting with the messaging system, in this case NATS)
        - type: link
          properties:
            target: nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]

    # Add a capability provider that implements `wasmcloud:messaging` using NATS
    - name: nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:canary
      traits:
        # Since the `nats` capability provider calls an component to handle messages
        # coming over subscriptions, this provider needs a unidirectional link to the
        # component that wil be called.
        #
        # Here we link the `nats` provider (the "source"), to the `echo` component (the "target"),
        # so that so the provider can deliver messages to the component (by invoking the wasmcloud:messaging/handler interface) .
        - type: link
          properties:
            target: catconsumer
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source_config:
              - name: simple-subscription
                properties:
                  subscriptions: wasmcloud.catconsumer

